t(specifications->manifest '("emacs-general"
			    ;"emacs-treesit-auto"
			    "emacs-smartparens"
			    "emacs-yasnippet"
			    "emacs-eglot"
			    "emacs-marginalia"
			    ;"emacs-dired-hide-dotfiles"
			    "emacs-ag"
			    "emacs-doom-modeline"
			    "emacs-modus-themes"
			    "emacs-dashboard"
			    "emacs-meow"
			    "emacs-which-key"
			    "emacs-vertico"
			    "emacs-vertico-posframe"
			    "emacs-corfu"
			    "emacs-orderless"
			    "emacs-pdf-tools"
			    "emacs-dirvish"
			    "emacs-racket-mode"
			    "emacs-flycheck"
			    ;"emacs-copilot"
			    "emacs-rainbow-delimiters"
			    "emacs-projectile"
			    "emacs-magit"
			    "emacs-org-modern"
			    "emacs-org-roam"
			    "emacs-org-fragtog"
			    "emacs-elfeed"
			    ;"emacs-elfeed-tube"
			    "emacs-cape"
			    "emacs-yasnippet-snippets"
			    "emacs-eat"))

;; Momo channel has packages not defined in guix packages
