(defun momo/meow-compat-setup ()
  "Configure mode-specific defaults for Meow.

The policy is:
- editing buffers start modal (`normal')
- external app/chat/terminal input starts pass-through-ish (`insert')
- read-only UI buffers start navigational (`motion')
- Dired keeps ranger-style local h/l navigation, so it starts in `motion'."
  (dolist (entry '((conf-mode . normal)
                   (prog-mode . normal)
                   (text-mode . normal)
                   (fundamental-mode . normal)
                   (minibuffer-mode . insert)
                   (eca-chat-mode . insert)
                   (eat-mode . insert)
                   (exwm-mode . insert)
                   (dashboard-mode . motion)
                   (dired-mode . motion)
                   (dirvish-directory-view-mode . motion)
                   (eww-mode . motion)
                   (help-mode . motion)
                   (messages-buffer-mode . motion)
                   (special-mode . motion)))
    (setf (alist-get (car entry) meow-mode-state-list) (cdr entry))))

(defun meow-setup ()
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
  (momo/meow-compat-setup)
  (meow-motion-overwrite-define-key
   '("j" . meow-next)
   '("k" . meow-prev)
   '("<escape>" . ignore))
  (meow-leader-define-key
   ;; SPC j/k will run the original command in MOTION state.
   '("j" . "H-j")
   '("k" . "H-k")
   ;; Use SPC (0-9) for digit arguments.
   '("1" . meow-digit-argument)
   '("2" . meow-digit-argument)
   '("3" . meow-digit-argument)
   '("4" . meow-digit-argument)
   '("5" . meow-digit-argument)
   '("6" . meow-digit-argument)
   '("7" . meow-digit-argument)
   '("8" . meow-digit-argument)
   '("9" . meow-digit-argument)
   '("0" . meow-digit-argument)
   '("/" . meow-keypad-describe-key)
   '("?" . meow-cheatsheet)
   ;; Ergonomic aliases.  The existing C-c leaders remain available as
   ;; fallbacks, and Meow's leader can still reach them as SPC m/o/n/c.
   '("b" . consult-buffer)
   '("m k" . packwiz-dispatch)
   '("o c" . org-capture)
   '("o r" . org-refile)
   '("n f" . org-roam-node-find)
   '("n c" . org-roam-capture)
   '("n i" . org-roam-node-insert)
   '("n j" . org-roam-dailies-capture-today)
   '("c r" . momo/reload-config)
   '("c o" . momo/open-config))
  (meow-normal-define-key
   '("0" . meow-expand-0)
   '("9" . meow-expand-9)
   '("8" . meow-expand-8)
   '("7" . meow-expand-7)
   '("6" . meow-expand-6)
   '("5" . meow-expand-5)
   '("4" . meow-expand-4)
   '("3" . meow-expand-3)
   '("2" . meow-expand-2)
   '("1" . meow-expand-1)
   '("-" . negative-argument)
   '(";" . meow-reverse)
   '("," . meow-inner-of-thing)
   '("." . meow-bounds-of-thing)
   '("[" . meow-beginning-of-thing)
   '("]" . meow-end-of-thing)
   '("a" . meow-append)
   '("A" . meow-open-below)
   '("b" . meow-back-word)
   '("B" . meow-back-symbol)
   '("c" . meow-change)
   '("d" . meow-delete)
   '("D" . meow-backward-delete)
   '("e" . meow-next-word)
   '("E" . meow-next-symbol)
   '("f" . meow-find)
   '("g" . meow-cancel-selection)
   '("G" . meow-grab)
   '("h" . meow-left)
   '("H" . meow-left-expand)
   '("i" . meow-insert)
   '("I" . meow-open-above)
   '("j" . meow-next)
   '("J" . meow-next-expand)
   '("k" . meow-prev)
   '("K" . meow-prev-expand)
   '("l" . meow-right)
   '("L" . meow-right-expand)
   '("m" . meow-join)
   '("n" . meow-search)
   '("o" . meow-block)
   '("O" . meow-to-block)
   '("p" . meow-yank)
   '("q" . meow-quit)
   '("Q" . meow-goto-line)
   '("r" . meow-replace)
   '("R" . meow-swap-grab)
   '("s" . meow-kill)
   '("t" . meow-till)
   '("u" . meow-undo)
   '("U" . meow-undo-in-selection)
   '("v" . meow-visit)
   '("w" . meow-mark-word)
   '("W" . meow-mark-symbol)
   '("x" . meow-line)
   '("X" . meow-goto-line)
   '("y" . meow-save)
   '("Y" . meow-sync-grab)
   '("z" . meow-pop-selection)
   '("'" . repeat)
   '("<escape>" . ignore)))

(use-package meow
  :config
  (meow-setup)
  (meow-global-mode 1)
  (setq meow-use-clipboard 1))


