;;; elfeed-config.el --- Elfeed RSS and YouTube feeds configuration -*- lexical-binding: t; -*-

(defcustom momo-youtube-channel-urls '("Kyle.Gabriel"
				  "Orthocast"
				  "MentisWave"
				  "Vercidium"
				  "DyerClips"
				  "ThePrimeagen"
				  "esorem"
				  "NewWorldReview"
				  "AtomicFrontier"
				  "orthodoxmemesquad503"
				  "VinceVintage"
				  "MentalOutlaw"
				  "Memology101"
				  "BlacktailStudio"
				  "Seraphim-Hamilton"
				  "joshbetts1022"
				  "aarthificial"
				  "LetsTalkReligion"
				  "TwoMinutePapers"
				  "JohnDoyle"
				  "redeemedzoomer6053"
				  "MicTheSnare"
				  "TechnoTim"
				  "GavinFreeborn"
				  "Exercise4CheatMeals"
				  "ZacBuilds"
				  "SebastianLague"
				  "veritasium"
				  "JoshuaWeissman"
				  "OrthodoxKyle"
				  "BrodieRobertson"
				  "TheLinuxEXP"
				  "CleoAbram"
				  "BibleIllustrated"
				  "EmperorLemon"
				  "Patristix"
				  "bycloudAI"
				  "EthanChlebowski"
				  "harmonyharmonyharmony"
				  "kurzgesagt"
				  "SystemCrafters"
				  "TheRubber"
				  "PatristicNectarFilms"
				  "living_orthodox"
				  "emacselements"
				  "Fireship"
				  "MarkRober"
				  "AIandGames"
				  "abcdw"
				  "TastingHistory"
				  "OrthodoxEthos"
				  "ChurchoftheEternalLogos"
				  "NoBoilerplate"
				  "t3ssel8r"
				  "aiexplained-official"
				  "dreamsofcode"
				  "JayDyer"
				  "PolyMatter"
				  "StosselTV"
				  "andiswerkstatt-ow4uw"
				  "DIYPerks"
				  "jubilee"
				  "QuantaScienceChannel"
				  "LinusTechTips")
  "List of YouTube channel URLs to process."
  :type 'list
  :group 'momo)

(defcustom momo-rss-feeds '("https://rsshub-production-7458.up.railway.app/twitter/user/crazyclipsonly/readable=1&showAuthorInTitle=1"
		      "https://rsshub-production-7458.up.railway.app/twitter/user/GlobalOrthodox/readable=1&showAuthorInTitle=1"
		      "https://rsshub-production-7458.up.railway.app/twitter/user/FrankHassleYT/readable=1&showAuthorInTitle=1"
		      "https://rsshub-production-7458.up.railway.app/twitter/user/Gentilenewsnet/readable=1&showAuthorInTitle=1"
		      "https://rsshub-production-7458.up.railway.app/twitter/user/wigger/readable=1&showAuthorInTitle=1"
		      "https://rsshub-production-7458.up.railway.app/twitter/user/DudespostingWs/readable=1&showAuthorInTitle=1"
		      "https://rsshub-production-7458.up.railway.app/twitter/user/WomenPostingLs/readable=1&showAuthorInTitle=1"
		      "https://rsshub-production-7458.up.railway.app/twitter/user/Tomhennessey69/readable=1&showAuthorInTitle=1"
		      "https://rsshub-production-7458.up.railway.app/twitter/user/OrthodoxEthos/readable=1&showAuthorInTitle=1"
		      "https://rsshub-production-7458.up.railway.app/twitter/user/banterwithb/readable=1&showAuthorInTitle=1"
		      "https://rsshub-production-7458.up.railway.app/twitter/user/lporiginalg/readable=1&showAuthorInTitle=1"
		      "https://rsshub-production-7458.up.railway.app/twitter/user/GarbageHuman23/readable=1&showAuthorInTitle=1"
		      "https://rsshub-production-7458.up.railway.app/twitter/user/Jay_D007/readable=1&showAuthorInTitle=1"
		      "https://rsshub-production-7458.up.railway.app/twitter/user/iamyesyouareno/readable=1&showAuthorInTitle=1"
		      "https://rsshub-production-7458.up.railway.app/twitter/user/AnaniasFather/readable=1&showAuthorInTitle=1"
		      "https://rsshub-production-7458.up.railway.app/twitter/user/MomsPostingLs/readable=1&showAuthorInTitle=1"
		      "https://rsshub-production-7458.up.railway.app/twitter/user/RealBroNat/readable=1&showAuthorInTitle=1"
		      "https://rsshub-production-7458.up.railway.app/twitter/user/Muhsoci0factors/readable=1&showAuthorInTitle=1"
		      "https://rsshub-production-7458.up.railway.app/twitter/user/reddit_lies/readable=1&showAuthorInTitle=1"
		      "https://rsshub-production-7458.up.railway.app/twitter/user/PicturesFoIder/readable=1&showAuthorInTitle=1"
		      "https://rsshub-production-7458.up.railway.app/twitter/user/FAFO_TV/readable=1&showAuthorInTitle=1"
		      "https://boards.4channel.org/g/index.rss")
  "List of rss feeds, twitter through rsshub"
  :type 'list
  :group 'momo)

(provide 'elfeed-config)
;;; elfeed-config.el ends here
