;;; guix-gold-palette.el --- shared face generator for guix-gold  -*- lexical-binding: t; -*-

;; One face spec set, fed a palette plist by guix-gold-theme.el (dark) and
;; guix-gold-light-theme.el (light).  Keeps the two variants from drifting.

(defun guix-gold--faces (p)
  "Return a list of `custom-theme-set-faces' specs from palette plist P."
  (let* ((bg      (plist-get p :bg))
         (bg-soft (plist-get p :bg-soft))
         (bg-hl   (plist-get p :bg-hl))
         (fg      (plist-get p :fg))
         (fg-dim  (plist-get p :fg-dim))
         (cursor  (plist-get p :cursor))
         (comment (plist-get p :comment))
         (keyword (plist-get p :keyword))   ; gold
         (builtin (plist-get p :builtin))   ; ember
         (string  (plist-get p :string))    ; green
         (type    (plist-get p :type))      ; periwinkle
         (quote-c (plist-get p :quote))     ; pink
         (error-c (plist-get p :error))     ; crimson
         (paren   (plist-get p :paren))
         (r0      (plist-get p :r0))
         (r1      (plist-get p :r1))
         (r2      (plist-get p :r2))
         (r3      (plist-get p :r3))
         (add-bg  (plist-get p :add-bg))
         (add-bg2 (plist-get p :add-bg-hi))
         (del-bg  (plist-get p :del-bg))
         (del-bg2 (plist-get p :del-bg-hi))
         (chg-bg  (plist-get p :chg-bg))
         (chg-bg2 (plist-get p :chg-bg-hi))
         (add-fg  (plist-get p :add-fg))
         (del-fg  (plist-get p :del-fg))
         (chg-fg  (plist-get p :chg-fg)))
    (list
     ;; ===== basics =====
     `(default   ((t (:background ,bg :foreground ,fg))))
     `(cursor    ((t (:background ,cursor))))
     `(region    ((t (:background ,bg-hl :extend t))))
     `(highlight ((t (:background ,bg-hl))))
     `(hl-line   ((t (:background ,bg-soft :extend t))))
     `(fringe    ((t (:background ,bg :foreground ,fg-dim))))
     `(vertical-border ((t (:foreground ,bg-hl))))
     `(window-divider ((t (:foreground ,bg-hl))))
     `(window-divider-first-pixel ((t (:foreground ,bg-hl))))
     `(window-divider-last-pixel  ((t (:foreground ,bg-hl))))
     `(minibuffer-prompt ((t (:foreground ,keyword :weight bold))))
     `(shadow    ((t (:foreground ,fg-dim))))
     `(link      ((t (:foreground ,type :underline t))))
     `(link-visited ((t (:foreground ,quote-c :underline t))))
     `(error     ((t (:foreground ,error-c :weight bold))))
     `(warning   ((t (:foreground ,builtin :weight bold))))
     `(success   ((t (:foreground ,string :weight bold))))
     `(escape-glyph ((t (:foreground ,quote-c))))
     `(homoglyph  ((t (:foreground ,quote-c))))
     `(trailing-whitespace ((t (:background ,error-c))))
     `(fill-column-indicator ((t (:foreground ,bg-hl))))
     `(line-number ((t (:foreground ,fg-dim :background ,bg))))
     `(line-number-current-line ((t (:foreground ,keyword :background ,bg-soft :weight bold))))
     `(tooltip ((t (:background ,bg-soft :foreground ,fg))))
     `(widget-field ((t (:background ,bg-soft :foreground ,fg))))
     `(widget-button ((t (:foreground ,type :weight bold))))
     `(custom-button ((t (:background ,bg-hl :foreground ,fg :box (:line-width 1 :color ,paren)))))
     `(custom-group-tag ((t (:foreground ,keyword :weight bold :height 1.1))))
     `(custom-variable-tag ((t (:foreground ,type :weight bold))))
     `(custom-state ((t (:foreground ,string))))

     ;; ===== font-lock (decisions locked) =====
     `(font-lock-comment-face           ((t (:foreground ,comment))))
     `(font-lock-comment-delimiter-face ((t (:foreground ,fg-dim))))
     `(font-lock-keyword-face           ((t (:foreground ,keyword))))
     `(font-lock-builtin-face           ((t (:foreground ,builtin))))
     `(font-lock-string-face            ((t (:foreground ,string))))
     `(font-lock-doc-face               ((t (:foreground ,string :slant italic))))
     `(font-lock-doc-markup-face        ((t (:foreground ,type))))
     `(font-lock-type-face              ((t (:foreground ,type))))
     `(font-lock-constant-face          ((t (:foreground ,quote-c))))
     `(font-lock-number-face            ((t (:foreground ,type))))
     `(font-lock-function-name-face     ((t (:foreground ,type))))
     `(font-lock-function-call-face     ((t (:foreground ,type))))
     `(font-lock-variable-name-face     ((t (:foreground ,fg))))
     `(font-lock-variable-use-face      ((t (:foreground ,fg))))
     `(font-lock-property-name-face     ((t (:foreground ,quote-c))))
     `(font-lock-property-use-face      ((t (:foreground ,quote-c))))
     `(font-lock-preprocessor-face      ((t (:foreground ,builtin))))
     `(font-lock-negation-char-face     ((t (:foreground ,error-c))))
     `(font-lock-escape-face            ((t (:foreground ,quote-c))))
     `(font-lock-regexp-grouping-backslash ((t (:foreground ,builtin))))
     `(font-lock-regexp-grouping-construct ((t (:foreground ,keyword))))
     `(font-lock-warning-face           ((t (:foreground ,error-c :weight bold))))

     ;; ===== parens / rainbow =====
     `(show-paren-match    ((t (:background ,bg-hl :foreground ,keyword :weight bold))))
     `(show-paren-mismatch ((t (:background ,error-c :foreground ,bg :weight bold))))
     `(rainbow-delimiters-depth-1-face ((t (:foreground ,r0))))
     `(rainbow-delimiters-depth-2-face ((t (:foreground ,r1))))
     `(rainbow-delimiters-depth-3-face ((t (:foreground ,r2))))
     `(rainbow-delimiters-depth-4-face ((t (:foreground ,r3))))
     `(rainbow-delimiters-depth-5-face ((t (:foreground ,r0))))
     `(rainbow-delimiters-depth-6-face ((t (:foreground ,r1))))
     `(rainbow-delimiters-depth-7-face ((t (:foreground ,r2))))
     `(rainbow-delimiters-depth-8-face ((t (:foreground ,r3))))
     `(rainbow-delimiters-depth-9-face ((t (:foreground ,r0))))
     `(rainbow-delimiters-unmatched-face  ((t (:foreground ,error-c :weight bold))))
     `(rainbow-delimiters-mismatched-face ((t (:foreground ,error-c :weight bold))))
     `(parinfer-smart-tab:indicator-face ((t (:foreground ,bg-hl))))

     ;; ===== search / matching =====
     `(isearch       ((t (:background ,keyword :foreground ,bg :weight bold))))
     `(isearch-group-1 ((t (:background ,quote-c :foreground ,bg))))
     `(isearch-group-2 ((t (:background ,type :foreground ,bg))))
     `(lazy-highlight ((t (:background ,bg-hl :foreground ,fg))))
     `(isearch-fail   ((t (:background ,error-c :foreground ,bg))))
     `(match          ((t (:background ,bg-hl :foreground ,keyword))))
     `(pulse-highlight-start-face ((t (:background ,bg-hl))))
     `(query-replace  ((t (:background ,quote-c :foreground ,bg))))

     ;; ===== mode line =====
     `(mode-line          ((t (:background ,bg-hl :foreground ,fg :box nil))))
     `(mode-line-active   ((t (:background ,bg-hl :foreground ,fg :box nil))))
     `(mode-line-inactive ((t (:background ,bg-soft :foreground ,fg-dim :box nil))))
     `(mode-line-emphasis ((t (:foreground ,keyword :weight bold))))
     `(mode-line-highlight ((t (:background ,bg-hl :foreground ,keyword))))
     `(mode-line-buffer-id ((t (:foreground ,fg :weight bold))))

     ;; ===== header line & tabs =====
     `(header-line ((t (:background ,bg-soft :foreground ,fg :box nil))))
     `(header-line-highlight ((t (:foreground ,keyword))))
     `(tab-bar             ((t (:background ,bg-soft :foreground ,fg-dim :box nil))))
     `(tab-bar-tab         ((t (:background ,bg-hl :foreground ,keyword :weight bold :box nil))))
     `(tab-bar-tab-inactive ((t (:background ,bg-soft :foreground ,fg-dim :box nil))))
     `(tab-bar-tab-group-current  ((t (:background ,bg-soft :foreground ,keyword :weight bold))))
     `(tab-bar-tab-group-inactive ((t (:background ,bg-soft :foreground ,fg-dim))))
     `(tab-bar-tab-ungrouped ((t (:background ,bg-soft :foreground ,fg-dim))))
     `(tab-line            ((t (:background ,bg-soft :foreground ,fg-dim :box nil))))
     `(tab-line-tab        ((t (:background ,bg-soft :foreground ,fg :box nil))))
     `(tab-line-tab-current ((t (:background ,bg-hl :foreground ,keyword :weight bold :box nil))))
     `(tab-line-tab-inactive ((t (:background ,bg-soft :foreground ,fg-dim :box nil))))
     `(tab-line-tab-modified ((t (:foreground ,builtin))))
     `(tab-line-highlight  ((t (:background ,bg-hl :foreground ,fg))))

     ;; ===== completion frameworks =====
     `(completions-common-part ((t (:foreground ,keyword :weight bold))))
     `(completions-first-difference ((t (:foreground ,builtin :weight bold))))
     `(completions-annotations ((t (:foreground ,fg-dim :slant italic))))
     `(completions-group-title ((t (:foreground ,type :slant italic))))
     `(completions-group-separator ((t (:foreground ,fg-dim :strike-through t))))
     `(vertico-current    ((t (:background ,bg-hl :extend t))))
     `(vertico-group-title ((t (:foreground ,type :slant italic))))
     `(vertico-group-separator ((t (:foreground ,fg-dim :strike-through t))))
     `(vertico-multiline  ((t (:foreground ,fg-dim))))
     `(corfu-default      ((t (:background ,bg-soft :foreground ,fg))))
     `(corfu-current      ((t (:background ,bg-hl :foreground ,fg))))
     `(corfu-bar          ((t (:background ,keyword))))
     `(corfu-border       ((t (:background ,bg-hl))))
     `(corfu-annotations  ((t (:foreground ,fg-dim))))
     `(orderless-match-face-0 ((t (:foreground ,r0 :weight bold))))
     `(orderless-match-face-1 ((t (:foreground ,r1 :weight bold))))
     `(orderless-match-face-2 ((t (:foreground ,r2 :weight bold))))
     `(orderless-match-face-3 ((t (:foreground ,r3 :weight bold))))
     `(marginalia-key         ((t (:foreground ,keyword))))
     `(marginalia-type        ((t (:foreground ,type))))
     `(marginalia-documentation ((t (:foreground ,fg-dim :slant italic))))
     `(marginalia-file-name   ((t (:foreground ,fg-dim))))
     `(marginalia-file-priv-dir ((t (:foreground ,type))))
     `(marginalia-file-priv-read ((t (:foreground ,string))))
     `(marginalia-file-priv-write ((t (:foreground ,builtin))))
     `(marginalia-file-priv-exec ((t (:foreground ,error-c))))
     `(marginalia-number      ((t (:foreground ,type))))
     `(marginalia-date        ((t (:foreground ,type))))
     `(marginalia-size        ((t (:foreground ,quote-c))))
     `(marginalia-mode        ((t (:foreground ,type))))
     `(marginalia-modified    ((t (:foreground ,builtin))))
     `(marginalia-char        ((t (:foreground ,quote-c))))
     `(marginalia-symbol      ((t (:foreground ,type))))
     `(marginalia-value       ((t (:foreground ,fg))))
     `(consult-file           ((t (:foreground ,fg))))
     `(consult-line-number    ((t (:foreground ,fg-dim))))
     `(consult-line-number-prefix ((t (:foreground ,fg-dim))))
     `(consult-line-number-wrapped ((t (:foreground ,builtin))))
     `(consult-async-split    ((t (:foreground ,builtin))))
     `(consult-async-running  ((t (:foreground ,keyword))))
     `(consult-async-finished ((t (:foreground ,string))))
     `(consult-async-failed   ((t (:foreground ,error-c))))
     `(consult-bookmark       ((t (:foreground ,type))))
     `(consult-key            ((t (:foreground ,keyword))))
     `(consult-imenu-prefix   ((t (:foreground ,fg-dim))))
     `(consult-preview-line   ((t (:background ,bg-hl :extend t))))
     `(consult-preview-cursor ((t (:background ,keyword :foreground ,bg))))
     `(consult-highlight-match ((t (:foreground ,keyword :weight bold))))

     ;; ===== diff / ediff / smerge =====
     `(diff-added      ((t (:background ,add-bg :foreground ,add-fg :extend t))))
     `(diff-removed    ((t (:background ,del-bg :foreground ,del-fg :extend t))))
     `(diff-changed    ((t (:background ,chg-bg :foreground ,chg-fg :extend t))))
     `(diff-indicator-added   ((t (:background ,add-bg :foreground ,add-fg))))
     `(diff-indicator-removed ((t (:background ,del-bg :foreground ,del-fg))))
     `(diff-indicator-changed ((t (:background ,chg-bg :foreground ,chg-fg))))
     `(diff-refine-added   ((t (:background ,add-bg2 :foreground ,add-fg))))
     `(diff-refine-removed ((t (:background ,del-bg2 :foreground ,del-fg))))
     `(diff-refine-changed ((t (:background ,chg-bg2 :foreground ,chg-fg))))
     `(diff-context    ((t (:foreground ,fg-dim))))
     `(diff-header     ((t (:background ,bg-soft :foreground ,keyword :weight bold :extend t))))
     `(diff-file-header ((t (:background ,bg-soft :foreground ,fg :weight bold :extend t))))
     `(diff-hunk-header ((t (:background ,bg-hl :foreground ,fg-dim :extend t))))
     `(diff-function   ((t (:foreground ,type))))
     `(diff-nonexistent ((t (:foreground ,fg-dim))))
     `(ediff-current-diff-A ((t (:background ,del-bg :extend t))))
     `(ediff-current-diff-B ((t (:background ,add-bg :extend t))))
     `(ediff-current-diff-C ((t (:background ,chg-bg :extend t))))
     `(ediff-current-diff-Ancestor ((t (:background ,bg-hl :extend t))))
     `(ediff-fine-diff-A ((t (:background ,del-bg2))))
     `(ediff-fine-diff-B ((t (:background ,add-bg2))))
     `(ediff-fine-diff-C ((t (:background ,chg-bg2))))
     `(ediff-fine-diff-Ancestor ((t (:background ,bg-hl))))
     `(ediff-even-diff-A ((t (:background ,bg-soft :extend t))))
     `(ediff-even-diff-B ((t (:background ,bg-soft :extend t))))
     `(ediff-even-diff-C ((t (:background ,bg-soft :extend t))))
     `(ediff-odd-diff-A ((t (:background ,bg-soft :extend t))))
     `(ediff-odd-diff-B ((t (:background ,bg-soft :extend t))))
     `(ediff-odd-diff-C ((t (:background ,bg-soft :extend t))))
     `(smerge-upper ((t (:background ,del-bg :extend t))))
     `(smerge-lower ((t (:background ,add-bg :extend t))))
     `(smerge-base  ((t (:background ,chg-bg :extend t))))
     `(smerge-markers ((t (:background ,bg-hl :foreground ,fg-dim :extend t))))
     `(smerge-refined-added   ((t (:background ,add-bg2 :foreground ,add-fg))))
     `(smerge-refined-removed ((t (:background ,del-bg2 :foreground ,del-fg))))

     ;; ===== magit =====
     `(magit-section-heading ((t (:foreground ,keyword :weight bold))))
     `(magit-section-heading-selection ((t (:foreground ,builtin :weight bold))))
     `(magit-section-highlight ((t (:background ,bg-soft :extend t))))
     `(magit-section-secondary-heading ((t (:foreground ,type :weight bold))))
     `(magit-header-line ((t (:background ,bg-soft :foreground ,keyword :weight bold :box nil))))
     `(magit-header-line-key ((t (:foreground ,keyword))))
     `(magit-header-line-log-select ((t (:foreground ,fg :weight bold))))
     `(magit-diff-added   ((t (:background ,add-bg :foreground ,add-fg :extend t))))
     `(magit-diff-added-highlight ((t (:background ,add-bg2 :foreground ,add-fg :extend t))))
     `(magit-diff-removed ((t (:background ,del-bg :foreground ,del-fg :extend t))))
     `(magit-diff-removed-highlight ((t (:background ,del-bg2 :foreground ,del-fg :extend t))))
     `(magit-diff-context ((t (:foreground ,fg-dim :extend t))))
     `(magit-diff-context-highlight ((t (:background ,bg-soft :foreground ,fg-dim :extend t))))
     `(magit-diff-hunk-heading ((t (:background ,bg-hl :foreground ,fg-dim :extend t))))
     `(magit-diff-hunk-heading-highlight ((t (:background ,bg-hl :foreground ,fg :weight bold :extend t))))
     `(magit-diff-hunk-heading-selection ((t (:background ,bg-hl :foreground ,builtin :extend t))))
     `(magit-diff-file-heading ((t (:foreground ,fg :weight bold))))
     `(magit-diff-file-heading-highlight ((t (:background ,bg-soft :foreground ,fg :weight bold :extend t))))
     `(magit-diff-lines-heading ((t (:background ,keyword :foreground ,bg :extend t))))
     `(magit-diffstat-added   ((t (:foreground ,add-fg))))
     `(magit-diffstat-removed ((t (:foreground ,del-fg))))
     `(magit-branch-local  ((t (:foreground ,type :weight bold))))
     `(magit-branch-remote ((t (:foreground ,string :weight bold))))
     `(magit-branch-current ((t (:foreground ,keyword :weight bold :box (:line-width 1 :color ,keyword)))))
     `(magit-tag ((t (:foreground ,keyword))))
     `(magit-hash ((t (:foreground ,fg-dim))))
     `(magit-log-author ((t (:foreground ,quote-c))))
     `(magit-log-date ((t (:foreground ,fg-dim))))
     `(magit-log-graph ((t (:foreground ,fg-dim))))
     `(magit-dimmed ((t (:foreground ,fg-dim))))
     `(magit-filename ((t (:foreground ,fg))))
     `(magit-bisect-good ((t (:foreground ,string))))
     `(magit-bisect-bad  ((t (:foreground ,error-c))))
     `(magit-bisect-skip ((t (:foreground ,keyword))))
     `(magit-blame-heading ((t (:background ,bg-soft :foreground ,fg :extend t))))
     `(magit-blame-hash ((t (:foreground ,fg-dim))))
     `(magit-blame-name ((t (:foreground ,quote-c))))
     `(magit-blame-date ((t (:foreground ,fg-dim))))
     `(magit-signature-good ((t (:foreground ,string))))
     `(magit-signature-bad  ((t (:foreground ,error-c))))
     `(magit-signature-untrusted ((t (:foreground ,keyword))))
     `(magit-cherry-equivalent ((t (:foreground ,quote-c))))
     `(magit-cherry-unmatched  ((t (:foreground ,type))))
     `(magit-reflog-commit  ((t (:foreground ,string))))
     `(magit-reflog-amend   ((t (:foreground ,quote-c))))
     `(magit-reflog-merge   ((t (:foreground ,string))))
     `(magit-reflog-checkout ((t (:foreground ,type))))
     `(magit-reflog-reset   ((t (:foreground ,error-c))))
     `(magit-reflog-rebase  ((t (:foreground ,quote-c))))
     `(magit-reflog-cherry-pick ((t (:foreground ,string))))
     `(magit-reflog-remote  ((t (:foreground ,type))))
     `(magit-reflog-other   ((t (:foreground ,type))))
     `(magit-process-ok ((t (:foreground ,string :weight bold))))
     `(magit-process-ng ((t (:foreground ,error-c :weight bold))))
     `(git-commit-summary ((t (:foreground ,keyword :weight bold))))
     `(git-commit-overlong-summary ((t (:foreground ,error-c :weight bold))))
     `(git-commit-nonempty-second-line ((t (:foreground ,error-c))))
     `(git-commit-comment-branch-local ((t (:foreground ,type))))
     `(git-commit-comment-branch-remote ((t (:foreground ,string))))
     `(git-commit-comment-heading ((t (:foreground ,keyword :weight bold))))
     `(git-commit-comment-file ((t (:foreground ,fg))))
     `(git-commit-comment-action ((t (:foreground ,builtin))))

     ;; ===== transient (magit / other menus) =====
     `(transient-heading ((t (:foreground ,keyword :weight bold))))
     `(transient-key      ((t (:foreground ,keyword))))
     `(transient-key-stay  ((t (:foreground ,string))))
     `(transient-key-exit  ((t (:foreground ,quote-c))))
     `(transient-key-noop  ((t (:foreground ,fg-dim))))
     `(transient-argument ((t (:foreground ,string :weight bold))))
     `(transient-value    ((t (:foreground ,type :weight bold))))
     `(transient-inactive-argument ((t (:foreground ,fg-dim))))
     `(transient-inactive-value ((t (:foreground ,fg-dim))))
     `(transient-enabled-suffix ((t (:background ,add-bg :foreground ,add-fg))))
     `(transient-disabled-suffix ((t (:background ,del-bg :foreground ,del-fg))))
     `(transient-unreachable ((t (:foreground ,fg-dim))))
     `(transient-unreachable-key ((t (:foreground ,fg-dim))))

     ;; ===== org =====
     `(org-level-1 ((t (:foreground ,r0 :weight bold :height 1.15))))
     `(org-level-2 ((t (:foreground ,r1 :weight bold :height 1.1))))
     `(org-level-3 ((t (:foreground ,r2 :weight bold))))
     `(org-level-4 ((t (:foreground ,r3 :weight bold))))
     `(org-level-5 ((t (:foreground ,r0))))
     `(org-level-6 ((t (:foreground ,r1))))
     `(org-level-7 ((t (:foreground ,r2))))
     `(org-level-8 ((t (:foreground ,r3))))
     `(org-document-title ((t (:foreground ,keyword :weight bold :height 1.3))))
     `(org-document-info ((t (:foreground ,type))))
     `(org-document-info-keyword ((t (:foreground ,fg-dim))))
     `(org-headline-done ((t (:foreground ,fg-dim :strike-through t))))
     `(org-todo ((t (:foreground ,error-c :weight bold))))
     `(org-done ((t (:foreground ,string :weight bold))))
     `(org-link ((t (:foreground ,type :underline t))))
     `(org-footnote ((t (:foreground ,type :underline t))))
     `(org-date ((t (:foreground ,type :underline t))))
     `(org-code ((t (:foreground ,string))))
     `(org-verbatim ((t (:foreground ,builtin))))
     `(org-block ((t (:background ,bg-soft :foreground ,fg :extend t))))
     `(org-block-begin-line ((t (:background ,bg-soft :foreground ,fg-dim :slant italic :extend t))))
     `(org-block-end-line ((t (:background ,bg-soft :foreground ,fg-dim :slant italic :extend t))))
     `(org-quote ((t (:foreground ,fg-dim :slant italic :extend t))))
     `(org-verse ((t (:foreground ,fg-dim :slant italic :extend t))))
     `(org-table ((t (:foreground ,type))))
     `(org-table-header ((t (:background ,bg-hl :foreground ,keyword :weight bold))))
     `(org-drawer ((t (:foreground ,fg-dim))))
     `(org-special-keyword ((t (:foreground ,fg-dim))))
     `(org-meta-line ((t (:foreground ,fg-dim :slant italic))))
     `(org-tag ((t (:foreground ,type :weight normal))))
     `(org-priority ((t (:foreground ,builtin))))
     `(org-checkbox ((t (:foreground ,keyword :weight bold))))
     `(org-checkbox-statistics-todo ((t (:foreground ,error-c))))
     `(org-checkbox-statistics-done ((t (:foreground ,string))))
     `(org-ellipsis ((t (:foreground ,fg-dim))))
     `(org-hide ((t (:foreground ,bg))))
     `(org-agenda-structure ((t (:foreground ,keyword :weight bold))))
     `(org-agenda-date ((t (:foreground ,type))))
     `(org-agenda-date-today ((t (:foreground ,keyword :weight bold))))
     `(org-agenda-date-weekend ((t (:foreground ,fg-dim))))
     `(org-agenda-done ((t (:foreground ,fg-dim))))
     `(org-scheduled ((t (:foreground ,string))))
     `(org-scheduled-today ((t (:foreground ,string :weight bold))))
     `(org-scheduled-previously ((t (:foreground ,builtin))))
     `(org-upcoming-deadline ((t (:foreground ,builtin))))
     `(org-warning ((t (:foreground ,error-c :weight bold))))
     `(org-column ((t (:background ,bg-soft))))
     `(org-column-title ((t (:background ,bg-hl :foreground ,keyword :weight bold))))

     ;; ===== markdown / shr / shrface (eca renders markdown) =====
     `(markdown-header-face-1 ((t (:foreground ,r0 :weight bold :height 1.15))))
     `(markdown-header-face-2 ((t (:foreground ,r1 :weight bold :height 1.1))))
     `(markdown-header-face-3 ((t (:foreground ,r2 :weight bold))))
     `(markdown-header-face-4 ((t (:foreground ,r3 :weight bold))))
     `(markdown-header-face-5 ((t (:foreground ,r0))))
     `(markdown-header-face-6 ((t (:foreground ,r1))))
     `(markdown-header-delimiter-face ((t (:foreground ,fg-dim))))
     `(markdown-code-face ((t (:background ,bg-soft :foreground ,string :extend t))))
     `(markdown-inline-code-face ((t (:foreground ,string))))
     `(markdown-pre-face ((t (:background ,bg-soft :foreground ,fg :extend t))))
     `(markdown-language-keyword-face ((t (:foreground ,fg-dim :slant italic))))
     `(markdown-link-face ((t (:foreground ,type))))
     `(markdown-url-face ((t (:foreground ,fg-dim :underline t))))
     `(markdown-link-title-face ((t (:foreground ,quote-c))))
     `(markdown-bold-face ((t (:foreground ,fg :weight bold))))
     `(markdown-italic-face ((t (:foreground ,fg :slant italic))))
     `(markdown-list-face ((t (:foreground ,keyword))))
     `(markdown-markup-face ((t (:foreground ,fg-dim))))
     `(markdown-blockquote-face ((t (:foreground ,fg-dim :slant italic))))
     `(markdown-metadata-key-face ((t (:foreground ,type))))
     `(markdown-metadata-value-face ((t (:foreground ,string))))
     `(markdown-gfm-checkbox-face ((t (:foreground ,keyword))))
     `(markdown-table-face ((t (:foreground ,type))))
     `(markdown-hr-face ((t (:foreground ,fg-dim))))
     `(shr-h1 ((t (:foreground ,r0 :weight bold :height 1.15))))
     `(shr-h2 ((t (:foreground ,r1 :weight bold :height 1.1))))
     `(shr-h3 ((t (:foreground ,r2 :weight bold))))
     `(shr-h4 ((t (:foreground ,r3 :weight bold))))
     `(shr-h5 ((t (:foreground ,r0))))
     `(shr-h6 ((t (:foreground ,r1))))
     `(shr-link ((t (:foreground ,type :underline t))))
     `(shr-code ((t (:foreground ,string))))
     `(shr-selected-link ((t (:background ,bg-hl :foreground ,type))))
     `(shrface-h1-face ((t (:foreground ,r0 :weight bold :height 1.15))))
     `(shrface-h2-face ((t (:foreground ,r1 :weight bold :height 1.1))))
     `(shrface-h3-face ((t (:foreground ,r2 :weight bold))))
     `(shrface-h4-face ((t (:foreground ,r3 :weight bold))))
     `(shrface-h5-face ((t (:foreground ,r0))))
     `(shrface-h6-face ((t (:foreground ,r1))))
     `(shrface-code-block-face ((t (:background ,bg-soft :foreground ,string :extend t))))
     `(shrface-verbatim ((t (:foreground ,builtin))))
     `(shrface-bullet-bullet-face ((t (:foreground ,keyword :weight bold))))
     `(shrface-item-number-face ((t (:foreground ,keyword))))

     ;; ===== Scheme: geiser / racket =====
     `(geiser-font-lock-autodoc-current-arg ((t (:foreground ,keyword :weight bold))))
     `(geiser-font-lock-autodoc-identifier ((t (:foreground ,type))))
     `(geiser-font-lock-error-link ((t (:foreground ,error-c :underline t))))
     `(geiser-font-lock-doc-link ((t (:foreground ,type :underline t))))
     `(geiser-font-lock-doc-title ((t (:foreground ,keyword :weight bold))))
     `(geiser-font-lock-repl-output ((t (:foreground ,string))))
     `(geiser-font-lock-repl-input ((t (:foreground ,fg))))
     `(geiser-font-lock-repl-prompt ((t (:foreground ,keyword :weight bold))))
     `(geiser-font-lock-xref-link ((t (:foreground ,type :underline t))))
     `(racket-keyword-argument-face ((t (:foreground ,quote-c))))
     `(racket-selfeval-face ((t (:foreground ,string))))
     `(racket-here-string-face ((t (:foreground ,string))))
     `(racket-reader-quoted-face ((t (:foreground ,quote-c))))
     `(racket-reader-syntax-quoted-face ((t (:foreground ,quote-c))))
     `(racket-xp-def-face ((t (:foreground ,type :weight bold))))
     `(racket-xp-use-face ((t (:foreground ,fg))))
     `(racket-xp-binding-lang-face ((t (:foreground ,type))))
     `(racket-xp-tail-target-face ((t (:underline (:style wave :color ,type)))))
     `(racket-xp-tail-position-face ((t (:underline (:style wave :color ,keyword)))))
     `(racket-xp-error-face ((t (:underline (:style wave :color ,error-c)))))
     `(racket-xp-unused-face ((t (:foreground ,fg-dim))))

     ;; ===== flycheck / flymake / compilation =====
     `(flycheck-error   ((t (:underline (:style wave :color ,error-c)))))
     `(flycheck-warning ((t (:underline (:style wave :color ,builtin)))))
     `(flycheck-info    ((t (:underline (:style wave :color ,type)))))
     `(flycheck-fringe-error   ((t (:foreground ,error-c))))
     `(flycheck-fringe-warning ((t (:foreground ,builtin))))
     `(flycheck-fringe-info    ((t (:foreground ,type))))
     `(flycheck-error-list-error   ((t (:foreground ,error-c))))
     `(flycheck-error-list-warning ((t (:foreground ,builtin))))
     `(flycheck-error-list-info    ((t (:foreground ,type))))
     `(flymake-error   ((t (:underline (:style wave :color ,error-c)))))
     `(flymake-warning ((t (:underline (:style wave :color ,builtin)))))
     `(flymake-note    ((t (:underline (:style wave :color ,type)))))
     `(flymake-error-echo   ((t (:foreground ,error-c))))
     `(flymake-warning-echo ((t (:foreground ,builtin))))
     `(flymake-note-echo    ((t (:foreground ,type))))
     `(compilation-error   ((t (:foreground ,error-c :weight bold))))
     `(compilation-warning ((t (:foreground ,builtin :weight bold))))
     `(compilation-info    ((t (:foreground ,type :weight bold))))
     `(compilation-line-number ((t (:foreground ,fg-dim))))
     `(compilation-column-number ((t (:foreground ,fg-dim))))
     `(compilation-mode-line-exit ((t (:foreground ,string :weight bold))))
     `(compilation-mode-line-fail ((t (:foreground ,error-c :weight bold))))
     `(compilation-mode-line-run  ((t (:foreground ,keyword :weight bold))))
     `(jinx-misspelled ((t (:underline (:style wave :color ,builtin)))))
     `(flyspell-incorrect ((t (:underline (:style wave :color ,error-c)))))
     `(flyspell-duplicate ((t (:underline (:style wave :color ,builtin)))))

     ;; ===== meow (modal editing) =====
     `(meow-normal-indicator ((t (:foreground ,bg :background ,keyword :weight bold))))
     `(meow-insert-indicator ((t (:foreground ,bg :background ,string :weight bold))))
     `(meow-motion-indicator ((t (:foreground ,bg :background ,type :weight bold))))
     `(meow-keypad-indicator ((t (:foreground ,bg :background ,quote-c :weight bold))))
     `(meow-beacon-indicator ((t (:foreground ,bg :background ,builtin :weight bold))))
     `(meow-normal-cursor ((t (:background ,keyword))))
     `(meow-insert-cursor ((t (:background ,string))))
     `(meow-motion-cursor ((t (:background ,type))))
     `(meow-keypad-cursor ((t (:background ,quote-c))))
     `(meow-beacon-cursor ((t (:background ,builtin))))
     `(meow-search-highlight ((t (:background ,bg-hl :foreground ,keyword))))
     `(meow-position-highlight-number ((t (:foreground ,keyword :weight bold))))
     `(meow-beacon-fake-selection ((t (:background ,bg-hl))))
     `(meow-region-cursor-1 ((t (:background ,keyword))))
     `(meow-region-cursor-2 ((t (:background ,type))))
     `(meow-region-cursor-3 ((t (:background ,quote-c))))

     ;; ===== which-key =====
     `(which-key-key-face ((t (:foreground ,keyword :weight bold))))
     `(which-key-group-description-face ((t (:foreground ,type))))
     `(which-key-command-description-face ((t (:foreground ,fg))))
     `(which-key-local-map-description-face ((t (:foreground ,string))))
     `(which-key-separator-face ((t (:foreground ,fg-dim))))
     `(which-key-note-face ((t (:foreground ,fg-dim))))
     `(which-key-special-key-face ((t (:foreground ,builtin :weight bold))))
     `(which-key-highlighted-command-face ((t (:foreground ,keyword :underline t))))

     ;; ===== dired / dirvish =====
     `(dired-directory ((t (:foreground ,type :weight bold))))
     `(dired-symlink ((t (:foreground ,quote-c))))
     `(dired-broken-symlink ((t (:foreground ,error-c :weight bold))))
     `(dired-header ((t (:foreground ,keyword :weight bold))))
     `(dired-mark ((t (:foreground ,keyword))))
     `(dired-marked ((t (:foreground ,keyword :weight bold))))
     `(dired-flagged ((t (:foreground ,error-c :weight bold))))
     `(dired-perm-write ((t (:foreground ,builtin))))
     `(dired-special ((t (:foreground ,quote-c))))
     `(dired-ignored ((t (:foreground ,fg-dim))))
     `(dirvish-hl-line ((t (:background ,bg-hl :extend t))))
     `(dirvish-git-commit-message-face ((t (:foreground ,fg-dim))))
     `(dirvish-header-line-face ((t (:background ,bg-soft :foreground ,fg))))
     `(dirvish-vc-needs-merge-face ((t (:foreground ,error-c))))
     `(dirvish-subtree-guide ((t (:foreground ,fg-dim))))
     `(dirvish-subtree-state ((t (:foreground ,fg-dim))))

     ;; ===== ansi / term (compilation, shells, eca tool output) =====
     `(ansi-color-black   ((t (:foreground ,bg :background ,bg))))
     `(ansi-color-red     ((t (:foreground ,error-c :background ,error-c))))
     `(ansi-color-green   ((t (:foreground ,string :background ,string))))
     `(ansi-color-yellow  ((t (:foreground ,keyword :background ,keyword))))
     `(ansi-color-blue    ((t (:foreground ,type :background ,type))))
     `(ansi-color-magenta ((t (:foreground ,quote-c :background ,quote-c))))
     `(ansi-color-cyan    ((t (:foreground ,type :background ,type))))
     `(ansi-color-white   ((t (:foreground ,fg :background ,fg))))
     `(ansi-color-bright-black   ((t (:foreground ,fg-dim :background ,fg-dim))))
     `(ansi-color-bright-red     ((t (:foreground ,error-c :background ,error-c))))
     `(ansi-color-bright-green   ((t (:foreground ,string :background ,string))))
     `(ansi-color-bright-yellow  ((t (:foreground ,builtin :background ,builtin))))
     `(ansi-color-bright-blue    ((t (:foreground ,type :background ,type))))
     `(ansi-color-bright-magenta ((t (:foreground ,quote-c :background ,quote-c))))
     `(ansi-color-bright-cyan    ((t (:foreground ,type :background ,type))))
     `(ansi-color-bright-white   ((t (:foreground ,fg :background ,fg))))
     `(term-color-black   ((t (:foreground ,fg-dim))))
     `(term-color-red     ((t (:foreground ,error-c))))
     `(term-color-green   ((t (:foreground ,string))))
     `(term-color-yellow  ((t (:foreground ,keyword))))
     `(term-color-blue    ((t (:foreground ,type))))
     `(term-color-magenta ((t (:foreground ,quote-c))))
     `(term-color-cyan    ((t (:foreground ,type))))
     `(term-color-white   ((t (:foreground ,fg))))

     ;; ===== doom-modeline =====
     `(doom-modeline-bar ((t (:background ,keyword))))
     `(doom-modeline-bar-inactive ((t (:background ,bg-soft))))
     `(doom-modeline-buffer-file ((t (:foreground ,fg :weight bold))))
     `(doom-modeline-buffer-modified ((t (:foreground ,builtin :weight bold))))
     `(doom-modeline-buffer-major-mode ((t (:foreground ,keyword :weight bold))))
     `(doom-modeline-buffer-path ((t (:foreground ,type))))
     `(doom-modeline-project-dir ((t (:foreground ,type :weight bold))))
     `(doom-modeline-info ((t (:foreground ,string))))
     `(doom-modeline-warning ((t (:foreground ,builtin))))
     `(doom-modeline-urgent ((t (:foreground ,error-c))))
     `(doom-modeline-debug ((t (:foreground ,fg-dim))))
     `(doom-modeline-highlight ((t (:foreground ,keyword))))
     `(doom-modeline-panel ((t (:background ,bg-hl :foreground ,keyword))))
     `(doom-modeline-evil-normal-state ((t (:foreground ,keyword))))
     `(doom-modeline-evil-insert-state ((t (:foreground ,string))))

     ;; ===== eca (agent client — the primary UI) =====
     ;; tabs
     `(eca-chat-tab-active-face ((t (:foreground ,keyword :weight bold))))
     `(eca-chat-tab-inactive-active-face ((t (:foreground ,fg-dim))))
     `(eca-tab-inactive-face ((t (:foreground ,fg-dim))))
     `(eca-doom-workspace-tab-running-face ((t (:foreground ,keyword))))
     `(eca-doom-workspace-tab-attention-face ((t (:foreground ,error-c :weight bold))))
     ;; titles / headings / labels
     `(eca-chat-title-face ((t (:foreground ,keyword :weight bold))))
     `(eca-chat-welcome-face ((t (:foreground ,keyword :weight bold))))
     `(eca-chat-file-change-label-face ((t (:foreground ,type :weight bold))))
     `(eca-chat-file-path-face ((t (:foreground ,type))))
     `(eca-chat-hook-label-face ((t (:foreground ,type))))
     `(eca-chat-reason-label-face ((t (:foreground ,fg-dim :slant italic))))
     `(eca-chat-mcp-tool-call-label-face ((t (:foreground ,type :weight bold))))
     `(eca-chat-subagent-tool-call-label-face ((t (:foreground ,type :weight bold))))
     `(eca-chat-subagent-steps-info-face ((t (:foreground ,fg-dim))))
     ;; messages / prompt
     `(eca-chat-user-messages-face ((t (:foreground ,type))))
     `(eca-chat-system-messages-face ((t (:foreground ,fg-dim))))
     `(eca-chat-queued-prompt-face ((t (:foreground ,fg-dim :slant italic))))
     `(eca-chat-steer-prompt-face ((t (:foreground ,builtin))))
     `(eca-chat-prompt-prefix-face ((t (:foreground ,keyword :weight bold))))
     `(eca-chat-prompt-stop-face ((t (:foreground ,error-c :weight bold))))
     ;; tool calls
     `(eca-chat-tool-call-accept-face ((t (:foreground ,string :weight bold))))
     `(eca-chat-tool-call-accept-and-remember-face ((t (:foreground ,string :weight bold))))
     `(eca-chat-tool-call-reject-face ((t (:foreground ,error-c :weight bold))))
     `(eca-chat-tool-call-keybinding-face ((t (:foreground ,keyword :weight bold))))
     `(eca-chat-tool-call-approval-content-face ((t (:foreground ,fg))))
     `(eca-chat-tool-call-spacing-face ((t (:foreground ,fg-dim))))
     `(eca-chat--tool-call-argument-key-face ((t (:foreground ,type))))
     `(eca-chat--tool-call-argument-value-face ((t (:foreground ,fg))))
     `(eca-chat--tool-call-table-key-face ((t (:foreground ,type :weight bold))))
     ;; shell commands
     `(eca-chat-shell-command-face ((t (:foreground ,builtin))))
     `(eca-chat-shell-command-remembered-face ((t (:foreground ,string))))
     `(eca-chat-shell-command-not-remembered-face ((t (:foreground ,fg-dim))))
     `(eca-chat-shell-command-always-asks-face ((t (:foreground ,keyword))))
     `(eca-chat-shell-command-breakdown-prefix-face ((t (:foreground ,fg-dim))))
     ;; context row
     `(eca-chat-context-agents-face ((t (:foreground ,type))))
     `(eca-chat-context-buffer-face ((t (:foreground ,type))))
     `(eca-chat-context-conversation-face ((t (:foreground ,type))))
     `(eca-chat-context-cursor-face ((t (:foreground ,type))))
     `(eca-chat-context-file-face ((t (:foreground ,type))))
     `(eca-chat-context-mcp-resource-face ((t (:foreground ,type))))
     `(eca-chat-context-repo-map-face ((t (:foreground ,type))))
     `(eca-chat-context-rules-face ((t (:foreground ,type))))
     `(eca-chat-context-skills-face ((t (:foreground ,type))))
     `(eca-chat-context-system-prompt-face ((t (:foreground ,type))))
     `(eca-chat-context-tool-calls-face ((t (:foreground ,type))))
     `(eca-chat-context-tool-definitions-face ((t (:foreground ,type))))
     `(eca-chat-context-free-face ((t (:foreground ,string))))
     `(eca-chat-context-compaction-marker-face ((t (:foreground ,builtin :weight bold))))
     `(eca-chat-context-unlinked-face ((t (:foreground ,fg-dim))))
     ;; tasks
     `(eca-chat-task-done-face ((t (:foreground ,string))))
     `(eca-chat-task-in-progress-face ((t (:foreground ,keyword :weight bold))))
     `(eca-chat-task-label-face ((t (:foreground ,fg))))
     `(eca-chat-task-label-in-progress-face ((t (:foreground ,keyword))))
     `(eca-chat-task-progress-face ((t (:foreground ,type))))
     `(eca-chat-task-prefix-face ((t (:foreground ,fg-dim))))
     ;; misc chat
     `(eca-chat-diff-view-face ((t (:foreground ,chg-fg :underline t :weight bold))))
     `(eca-chat-elapsed-time-face ((t (:foreground ,fg-dim))))
     `(eca-chat-time-face ((t (:foreground ,fg-dim))))
     `(eca-chat-usage-string-face ((t (:foreground ,fg-dim))))
     `(eca-chat-flag-face ((t (:foreground ,builtin))))
     `(eca-chat-command-description-face ((t (:foreground ,fg-dim))))
     `(eca-chat-load-more-face ((t (:foreground ,type :underline t))))
     `(eca-chat-resume-link-face ((t (:foreground ,type :underline t))))
     `(eca-chat-rollback-face ((t (:foreground ,error-c))))
     `(eca-chat-approval-modeline-face ((t (:foreground ,keyword :weight bold))))
     `(eca-chat-question-face ((t (:foreground ,keyword :weight bold))))
     `(eca-chat-question-description-face ((t (:foreground ,fg-dim))))
     `(eca-chat-question-option-face ((t (:foreground ,type))))
     `(eca-chat-option-key-face ((t (:foreground ,keyword :weight bold))))
     `(eca-chat-option-value-face ((t (:foreground ,fg))))
     ;; Background-only: eca overlays these across whole expanded blocks and
     ;; sets :background dynamically per theme.  A :foreground here would tint
     ;; ALL block content (e.g. question options, Cancel) one flat color,
     ;; clobbering the per-element font-lock faces underneath.
     `(eca-chat-expandable-block-1-face ((t (:extend t))))
     `(eca-chat-expandable-block-2-face ((t (:extend t))))
     `(eca-chat-trust-on-face ((t (:foreground ,string :weight bold))))
     `(eca-chat-trust-off-face ((t (:foreground ,error-c :weight bold))))
     ;; completion overlay / rewrite
     `(eca-completion-overlay-face ((t (:foreground ,fg-dim :slant italic))))
     `(eca-rewrite-overlay-face ((t (:background ,bg-soft :extend t))))
     `(eca-rewrite-overlay-hover-face ((t (:background ,bg-hl :extend t))))
     `(eca-rewrite-in-progress-prefix-face ((t (:foreground ,keyword))))
     `(eca-rewrite-ready-prefix-face ((t (:foreground ,string))))
     `(eca-rewrite-model-face ((t (:foreground ,type))))
     ;; jobs
     `(eca-jobs-status-completed-face ((t (:foreground ,string))))
     `(eca-jobs-status-failed-face ((t (:foreground ,error-c))))
     `(eca-jobs-status-running-face ((t (:foreground ,keyword))))
     `(eca-jobs-status-killed-face ((t (:foreground ,fg-dim))))
     `(eca-jobs-button-kill-face ((t (:foreground ,error-c :weight bold))))
     `(eca-jobs-button-output-face ((t (:foreground ,type))))
     `(eca-jobs-chat-separator-face ((t (:foreground ,fg-dim))))
     ;; mcp
     `(eca-mcp-details-button-face ((t (:foreground ,type))))
     `(eca-mcp-details-button-enable-face ((t (:foreground ,string :weight bold))))
     `(eca-mcp-details-button-disable-face ((t (:foreground ,error-c :weight bold))))
     `(eca-mcp-details-button-logout-face ((t (:foreground ,error-c))))
     `(eca-mcp-details-button-stop-face ((t (:foreground ,builtin))))
     `(eca-mcp-details-tool-face ((t (:foreground ,fg))))
     `(eca-mcp-details-tool-disabled-face ((t (:foreground ,fg-dim))))
     `(eca-mcp-details-requires-auth-face ((t (:foreground ,builtin))))
     `(eca-mcp-details-command-value-face ((t (:foreground ,string))))
     ;; providers
     `(eca-providers-authenticated-face ((t (:foreground ,string :weight bold))))
     `(eca-providers-unauthenticated-face ((t (:foreground ,error-c))))
     `(eca-providers-local-face ((t (:foreground ,type))))
     `(eca-providers-model-face ((t (:foreground ,fg))))
     `(eca-providers-section-face ((t (:foreground ,keyword :weight bold))))
     `(eca-providers-button-face ((t (:foreground ,type))))
     `(eca-providers-button-logout-face ((t (:foreground ,error-c))))
     `(eca-providers-auth-info-face ((t (:foreground ,fg-dim))))
     ;; settings / tables / workspaces
     `(eca-settings-heading ((t (:foreground ,keyword :weight bold))))
     `(eca-table-header-face ((t (:foreground ,keyword :weight bold))))
     `(eca-table-separator-face ((t (:foreground ,fg-dim))))
     `(eca-table-pipe-face ((t (:foreground ,fg-dim))))
     `(eca-table-row-even-face ((t (:background ,bg-soft :extend t))))
     `(eca-table-action-bar-face ((t (:foreground ,fg-dim))))
     `(eca-table-action-key-face ((t (:foreground ,keyword :weight bold))))
     `(eca-workspaces-tree-chat-details-face ((t (:foreground ,fg-dim))))
     `(eca-workspaces-tree-chat-idle-face ((t (:foreground ,fg-dim))))
     `(eca-workspaces-tree-chat-loading-face ((t (:foreground ,keyword))))

     ;; ===== xref / eldoc / misc =====
     `(xref-file-header ((t (:foreground ,keyword :weight bold))))
     `(xref-line-number ((t (:foreground ,fg-dim))))
     `(xref-match ((t (:background ,bg-hl :foreground ,keyword))))
     `(eldoc-highlight-function-argument ((t (:foreground ,keyword :weight bold))))
     `(highlight-numbers-number ((t (:foreground ,type))))
     `(hl-todo ((t (:foreground ,builtin :weight bold))))
     `(comint-highlight-prompt ((t (:foreground ,keyword :weight bold))))
     `(comint-highlight-input ((t (:foreground ,fg :weight bold))))
     `(button ((t (:foreground ,type :underline t))))
     `(help-key-binding ((t (:background ,bg-soft :foreground ,keyword :box (:line-width 1 :color ,paren)))))
     `(info-menu-header ((t (:foreground ,keyword :weight bold))))
     `(info-title-1 ((t (:foreground ,r0 :weight bold))))
     `(info-title-2 ((t (:foreground ,r1 :weight bold))))
     `(Info-quoted ((t (:foreground ,string))))
     `(bookmark-face ((t (:foreground ,keyword)))))))

(provide 'guix-gold-palette)
;;; guix-gold-palette.el ends here
